services:
  - type: web
    name: sisbar
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn sisbar_config.wsgi:application"
    plan: free
    autoDeploy: true
    envVars:
      - key: SECRET_KEY
        sync: false
      - key: DEBUG
        value: false
      - key: DATABASE_URL
        fromDatabase:
          name: sisbar-db
          property: connectionString
      - key: EMAIL_HOST_USER
        sync: false
      - key: EMAIL_HOST_PASSWORD
        sync: false

databases:
  - name: sisbar-db
    plan: free
